config/routes.rb
Rails.application.routes.draw do


  resources :galleries
  
  root to: 'rooms#statement'
  post 'rooms/disco' => 'rooms#disco'
  
  get 'discussion' => 'rooms#discussion', as: :discussion
  get 'contact' => 'rooms#contact', as: :contact
  get 'room/:id/edit' => 'rooms#edit', as: :edit_room_info
  patch 'room/:id/update' => 'rooms#update', as: :room
  post '/contact' => 'rooms#send_email', as: :send_email
  
  get 'users/login' => 'users#login', as: :login
  get 'users/logout' => 'users#logout', as: :logout
  get 'users/new' => 'users#new', as: :new_user
  post 'users/login' => 'users#submit_login', as: :submit_login
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  post 'users/new' => 'users#create', as: :create_user
  delete 'users/:id' => 'users#destroy', as: :delete_account
  get 'users/newAdmin' => 'users#new_admin', as: :create_new_admin
  patch 'users/update' => 'users#update_password', as: :update_password
  
  post 'carts/addItem' => 'carts#add_item_to_cart'
  post 'carts/removeItems' => 'carts#remove_items_from_cart'
  get 'carts/show' => 'carts#show'
  delete 'carts/clear' => 'carts#clear_cart'
  
  mount ActionCable.server => '/cable'

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :presence => true, :uniqueness => true
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :validate, only: [:new_admin]
  
  def login
    @user = User.new
  end
  
  
  def submit_login
    user = User.find_by(username: params[:user][:username])
    
    if !user.nil?
      if user.try(:authenticate, params[:user][:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        redirect_to login_path, flash: {notice: 'incorrect password'}
      end
    else
      redirect_to login_path, flash: {notice: 'user does not exist'}
    end
  end
  
  
  def logout
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_path, flash: {notice: 'successfully logged out'}
  end
  

  def new
    @user = User.new
  end
  
  
  def create
    user = User.new(user_params)
    if !session[:user_id].nil? && @current_user.admin
      user.admin = true
    else
      user.admin = false
    end
    if params[:user][:password].eql? params[:user][:password_confirmation]
      if user.save
        if @current_user.eql? nil
          session[:user_id] = user.id
        end
        redirect_to root_path, flash: {notice: "created new account"}
      else
        redirect_to new_user_path, flash: {notice: "sorry, your username is already taken"}
      end
    else
      redirect_to new_user_path, flash: {notice: "one or more fields is incorrect, please check that your passwords match"}
    end
  end
  
  
  def destroy
    @current_user.destroy
    session[:user_id] = nil
    redirect_to root_path flash: { notice: "account destroyed" }
  end

  def update_password
    if @current_user.try :authenticate, params[:user][:old_password]
      if params[:user][:new_password].eql? params[:user][:password_confirmation]
        @current_user.password = params[:user][:new_password]
        if @current_user.save
          redirect_to edit_user_path(id: @current_user.id), flash: { notice: "password updated" }
        else
          redirect_to edit_user_path(id: @current_user.id), flash: { notice: "could not update user" }
        end
      else
        redirect_to edit_user_path(id: @current_user.id), flash: {notice: "passwords do not match" }
      end
    else
      redirect_to edit_user_path(id: @current_user.id), flash: {notice: "incorrect password"}
    end
  end

  def edit
  end
  
  def new_admin
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% unless flash[:notice].nil? %>
	<h6 id='error' class="notice" ><%= flash[:notice] %></h6>
<% end %>

<div class="login-container">
<%= form_for :user, url: create_user_path do |f| %>
	<fieldset>
  		<legend><p>Login</p></legend>
  		
  		<table>
  			<tr>
  				<div class="field">
    				<td><%= f.label 'username:' %></td>
    				<td class="indent"><%= f.text_field :username %></td>
  				</div>
			</tr>
			
			<tr>
  				<div class="field">
    				<td><%= f.label 'password:' %></td>
    				<td class="indent"><%= f.password_field :password %></td>
	  			</div>
  		  	</tr>
  		  	
  		  	<tr>
	  		  	<div class="field">
    				<td><%= f.label 'confirm password:' %></td>
    				<td class="indent"><%= f.password_field :password_confirmation %></td>
	  			</div>
  			</tr>
  		</table>
  		<div class="field">
    		<%= f.submit 'Login', :class => 'submit-button' %>
  		</div>
  	</fieldset>
<% end %>  	
</div>

app/views/users/edit.html.erb
<h2 class="page-header" >Accounts Page</h2>

<% unless flash[:notice].nil? %>
	<h6 id='error' class="notice" ><%= flash[:notice] %></h6>
<% end %>

<div class="login-container">
<%= form_for :user, url: update_password_path, method: :patch do |f| %>
	<fieldset>
  		<legend><p>Login</p></legend>
  		
  		<table>
  			<tr>
  				<div class="field">
    				<td><%= f.label 'Old Password' %></td>
    				<td class="indent"><%= f.text_field :old_password %></td>
  				</div>
			</tr>
			
			<tr>
  				<div class="field">
    				<td><%= f.label 'New Password:' %></td>
    				<td class="indent"><%= f.password_field :new_password %></td>
	  			</div>
  		  	</tr>
  		  	
  		  	<tr>
	  		  	<div class="field">
    				<td><%= f.label 'Confirm Password:' %></td>
    				<td class="indent"><%= f.password_field :password_confirmation %></td>
	  			</div>
  			</tr>
  		</table>
  		<div class="field">
    		<%= f.submit 'Save Password', :class => 'submit-button' %>
  		</div>
  	</fieldset>
<% end %>  	
</div>

<% if @current_user.admin %>
	<%= button_to "Create New Admin", create_new_admin_path, class: :settings_button, method: :get %>
<% end %>

<%= button_to "Delete Account", delete_account_path(@current_user), class: :settings_button, method: :delete%>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h2 class="page-header">Login</h2>

<% unless flash[:notice].nil? %>
	<h6 id='error' class="notice" ><%= flash[:notice] %></h6>
<% end %>

<div class="login-container">
<%= form_for @user, url: submit_login_path do |f| %>
	<fieldset>
  		<legend><p>Login</p></legend>
  		
  		<table>
  			<tr>
  				
  				<div class="field">
    				<td><%= f.label 'username:' %></td>
    				<td class="indent"><%= f.text_field :username %></td>
  				</div>
			</tr>
			
			<tr>
  				<div class="field">
    				<td><%= f.label 'password:' %></td>
    				<td class="indent"><%= f.password_field :password %></td>
	  			</div>
  		  	</tr>
  		  	
  		</table>
  		<div class="field">
    		<%= f.submit 'Login', :class => 'submit-button' %>
  		</div>
  	</fieldset>
<% end %>  	
<span><%= link_to 'Create A New Account', new_user_path, :class => 'basic-link' %></span>
</div>



app/views/users/new.html.erb
<h2 class="page-header">Create New Account</h2>

<%= render 'form', user: @user %>

app/views/users/new_admin.html.erb
<h2 class="page-header" >Create A New Admin User</h2>
<p class="page-description">Create a new administrator account below, you will be able to change the account password later</p>

<%= render 'form', user: @user %>