config/routes.rb
Rails.application.routes.draw do


  resources :galleries
  
  root to: 'rooms#statement'
  post 'rooms/disco' => 'rooms#disco'
  
  get 'discussion' => 'rooms#discussion', as: :discussion
  get 'contact' => 'rooms#contact', as: :contact
  get 'room/:id/edit' => 'rooms#edit', as: :edit_room_info
  patch 'room/:id/update' => 'rooms#update', as: :room
  post '/contact' => 'rooms#send_email', as: :send_email
  
  get 'users/login' => 'users#login', as: :login
  get 'users/logout' => 'users#logout', as: :logout
  get 'users/new' => 'users#new', as: :new_user
  post 'users/login' => 'users#submit_login', as: :submit_login
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  post 'users/new' => 'users#create', as: :create_user
  delete 'users/:id' => 'users#destroy', as: :delete_account
  get 'users/newAdmin' => 'users#new_admin', as: :create_new_admin
  patch 'users/update' => 'users#update_password', as: :update_password
  
  post 'carts/addItem' => 'carts#add_item_to_cart'
  post 'carts/removeItems' => 'carts#remove_items_from_cart'
  get 'carts/show' => 'carts#show'
  delete 'carts/clear' => 'carts#clear_cart'
  
  mount ActionCable.server => '/cable'

end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  layout "no_sidebar", only: [:discussion]
  before_action :get_messages, only: [:discussion]
  
  def get_messages
    @messages = Message.order(:created_at => :desc)
    @connections = ActionCable.server.connections.length
  end
  
  def show
    @galleries = Gallery.all
    @images = @galleries.map{|g| g.image(:large)}
  end
  
  
  def discussion
    
  end
  
  
  def statement
    @info = Room.find_by(key: "statement")
    @info.value = @info.value.gsub '\n', '<br />'
  end
  
  
  
  def contact
    @info = Room.find_by(key: "contact")
    @info.value = @info.value.gsub '\n', '<br />'
  end
  
  
  
  def update
    @info = Room.find(params[:id])
    respond_to do |format|
      if @info.update(room_params)
        format.html { redirect_to root_path, notice: 'Room info was successfully updated.' }
      end
    end
  end
  
  
  
  def edit
    @info = Room.find(params[:id])
    
  end
  
  
  
  def send_email
    puts params[:email_info][:sender_email]
    puts params[:email_info][:email_content]
    #MailMailer.send_mail(params[:email_info][:sender_email], params[:email_info][:email_content]).deliver
    redirect_to root_path
  end

  
  
  private  
  
    def room_params
      params.require(:room).permit(:key, :value)
    end
    
    def validate
      if session[:user_id].nil? || !@current_user.admin
        redirect_to root_path
      end
    end
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb

<div class="room-container" >

	
	<div class="statement-container" >
		<%= form_for info do |f| %>
			<p><%= f.text_area :value, class: 'text-area' %></p>
			<%= f.submit "update" %>
		<% end %>
	</div>
</div>

app/views/rooms/contact.html.erb


<div class="room-container" >
	<div class="statement-container" >
		<p><%= raw @info.value %></p>
	</div>
</div>

<div id='admin-links'>
	<% if !session[:user_id].nil? && @current_user.admin %>
		<%= link_to 'Edit', edit_room_info_path(@info) %>
	<% end %>
</div>

app/views/rooms/discussion.html.erb
<h2>Welcome To The Discussion</h2>

<% if !session[:user_id].nil? %>
	<input type="hidden" id="user-name" value="<%= @current_user.username %>">
<% else %>
	<input type="hidden" id="user-name" value="">
<% end %>

<div id="messages-container">
	<span class="pointer-cursor chat-title" onclick="toggleExpand()">chat window -- people: <p id='connections'><%= @connections %></p></span>
	<textarea id="message-content" data-behavior="message-content-box" onkeyup="room.checkSendMessage(event)"></textarea>
	<div id="messages-inner">	
    	<div id="messages">
			<%= render @messages %>
		</div>
	</div>
</div>

app/views/rooms/edit.html.erb
<div id='secondary-header'></div>

<%= render 'form', info: @info %>

app/views/rooms/statement.html.erb
<div id='secondary-header'></div>
<% unless flash[:notice].nil? %>
	<h6 id='error' class="notice" ><%= flash[:notice] %></h6>
<% end %>

<div class="room-container" >
	<div class="statement-container" >
		<p><%= raw @info.value %></p>
	</div>
</div>

<div id='admin-links'>
	<% if !session[:user_id].nil? && @current_user.admin %>
		<%= link_to 'Edit', edit_room_info_path(@info) %>
	<% end %>
</div>

