config/routes.rb
Rails.application.routes.draw do


  resources :galleries
  
  root to: 'rooms#statement'
  post 'rooms/disco' => 'rooms#disco'
  
  get 'discussion' => 'rooms#discussion', as: :discussion
  get 'contact' => 'rooms#contact', as: :contact
  get 'room/:id/edit' => 'rooms#edit', as: :edit_room_info
  patch 'room/:id/update' => 'rooms#update', as: :room
  post '/contact' => 'rooms#send_email', as: :send_email
  
  get 'users/login' => 'users#login', as: :login
  get 'users/logout' => 'users#logout', as: :logout
  get 'users/new' => 'users#new', as: :new_user
  post 'users/login' => 'users#submit_login', as: :submit_login
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  post 'users/new' => 'users#create', as: :create_user
  delete 'users/:id' => 'users#destroy', as: :delete_account
  get 'users/newAdmin' => 'users#new_admin', as: :create_new_admin
  patch 'users/update' => 'users#update_password', as: :update_password
  
  post 'carts/addItem' => 'carts#add_item_to_cart'
  post 'carts/removeItems' => 'carts#remove_items_from_cart'
  get 'carts/show' => 'carts#show'
  delete 'carts/clear' => 'carts#clear_cart'
  
  mount ActionCable.server => '/cable'

end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_attached_file :image, styles: { large: "600x600>", thumb: "150x150#" }, s3_protocol: :https, s3_host_name: 's3-us-west-2.amazonaws.com', default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :validate, only: [:new, :edit, :update, :destroy]
  
  def index
    search_term = params[:search_term]
    if search_term.eql? 'all'
      @galleries = Gallery.all
    else
      @galleries = Gallery.where(:category => search_term)
    end
  end
  

  def show
  end

  def new
    @gallery = Gallery.new
  end

  def edit
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to @gallery, flash: {notice: "Gallery was successfully created."}
    else
      redirect_to root_path flash: {notice: "could not create gallery item"}
    end
  end

  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :description, :image, :price, :category)
    end
    
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, html: { multipart: true } do |f| %>

  	<% if gallery.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      		<ul>
	      	<% gallery.errors.full_messages.each do |message| %>
    	    	<li><%= message %></li>
    	  	<% end %>
	      	</ul>
    	</div>
	<% end %>

	<div class='new-gallery-container'>
		
		<table>
			<tr>
				<div class='field'>	
					<td><span class='gallery-label'>Title:</span></td>
					<td class="indent"><%= f.text_field :title, :class => 'gallery-field' %></td>
				</div>
			</tr>
			<tr>
				<div class="field">
    				<td><span class='gallery-label'>Image:</span></td>
    				<td class="indent"><%= f.file_field :image, :class => 'gallery-image-field' %></td>
		  		</div> 
			</tr>
			<tr>
				<div class="field">
					<td><span class='gallery-label'>Price:</span></td>
					<td class="indent"><%= f.text_field :price, :class => 'gallery-field'%></td>
				</div>
			</tr>
			<tr>
				<div class="field">
					<td><span class="gallery-label">Category</span></td>
					<td class="indent"><%= f.text_field :category, :class => 'gallery-field'%></td>
				</div>
			</tr>
		</table>
		
		<div class='field'>
			<%= f.label 'description:', :class => 'gallery-label' %>
			<%= f.text_area :description, :class => 'gallery-description-field' %>
		</div>
		

		<%= f.submit 'Create', :class => 'submit-button' %>
		<%= link_to 'Cancel', galleries_path, :class => 'cancel-button' %>

	</div>
<% end %>

app/views/galleries/edit.html.erb
<div id='secondary-header'></div>

<%= render 'form', gallery: @gallery %>

app/views/galleries/index.html.erb
<div id='secondary-header'></div>

<br />

<% if !session[:user_id].nil? && @current_user.admin %>
	<%= link_to 'New Galley Image', new_gallery_path, :class => 'admin-button' %>
<% end %>

<div id="gallery-page-container" >
	<% @galleries.each do |item| %>
		<div class="gallery-component-div">
			<%= react_component('GalleryParent', { title: item.title, image_url: item.image.url(:thumb), price: item.price, description: item.description, id: item.id, loggedOut: @cart.nil? }) %>
		</div>
	<% end %>
</div>

app/views/galleries/new.html.erb
<div id='secondary-header'></div>
<%= render 'form', gallery: @gallery %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="image-container">
	<div class="show-header-container">
		<p><%= @gallery.title %></p>
	</div>
	
	<%= image_tag @gallery.image.url(:large), :class => "show-image"%>
	
	<div id='add-to-cart-container'>
		<span id='cart-span'><%= image_tag 'Cart-icon.png', class: 'cart-icon'%></span>
		<% if @cart.nil? %>
			<span onclick="window.location.href = '/users/login';">Add To Cart</span>
		<% else %>
			<span onclick="cart.addItem(<%= @gallery.id %>)">Add To Cart</span>
		<% end %>
		<span>$<%= '%.2f' % @gallery.price %></span>
	</div>
	
	<div class="show-description-container">
		<h6>Description:</h6>
		<span><%= @gallery.description %></span>
	</div>
	
</div>

<div id='admin-links'>
	<% if !session[:user_id].nil? && @current_user.admin %>
		<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
		<%= link_to 'Delete', @gallery, method: :delete, data: { confirm: 'Are you sure?' } %> |
		<%= link_to 'Back', galleries_path %>
	<% end %>
</div>