config/routes.rb
Rails.application.routes.draw do


  resources :galleries
  
  root to: 'rooms#statement'
  post 'rooms/disco' => 'rooms#disco'
  
  get 'discussion' => 'rooms#discussion', as: :discussion
  get 'contact' => 'rooms#contact', as: :contact
  get 'room/:id/edit' => 'rooms#edit', as: :edit_room_info
  patch 'room/:id/update' => 'rooms#update', as: :room
  post '/contact' => 'rooms#send_email', as: :send_email
  
  get 'users/login' => 'users#login', as: :login
  get 'users/logout' => 'users#logout', as: :logout
  get 'users/new' => 'users#new', as: :new_user
  post 'users/login' => 'users#submit_login', as: :submit_login
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  post 'users/new' => 'users#create', as: :create_user
  delete 'users/:id' => 'users#destroy', as: :delete_account
  get 'users/newAdmin' => 'users#new_admin', as: :create_new_admin
  patch 'users/update' => 'users#update_password', as: :update_password
  
  post 'carts/addItem' => 'carts#add_item_to_cart'
  post 'carts/removeItems' => 'carts#remove_items_from_cart'
  get 'carts/show' => 'carts#show'
  delete 'carts/clear' => 'carts#clear_cart'
  
  mount ActionCable.server => '/cable'

end

app/views/layouts/_cart.html.erb
<ul>
  	<% @cart.cart_items.each do |c| %>
  		<li class='side-bar-item'>
  			<%= link_to c.gallery.title, c.gallery %><a class='quantity'> x <%= c.quantity %></a>
  		</li>
  	<% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<div id='side-bar'>
  	<span class="toggle-show" onclick='toggleSidebar(this)' data-section='search-items'>+ </span><span class='side-bar-title'>Search</span>
  		<div id='search-items'>
  			<ul id='search-items'>
  				<% @categories.each do |c| %>
  					<li class='side-bar-item'>
  						<%= link_to c, galleries_path( :search_term => c ) %>
  					</li>
  				<% end %>
  			</ul>
  		</div>
  	<span class='toggle-show' onclick='toggleSidebar(this)' data-section='cart-items'>+ </span><span class='side-bar-title'>Cart</span>
  	
  	<% if !@cart.nil? %>
  		<div id='cart-items'>
			<%= render :partial => '/layouts/cart' %>
  		</div>
  	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiffany Nelson</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  	
	<div class='header-color'>
	</div>

	<div class='header'>
	  	<h1 class='web-header-container'><span class="web-header">T i f f a n y</span><span class="web-header two">N e l s o n</span></h1>
	  	<div class='header-description'><em>artist | metal smith | maker</em></div>
	  	<span class="login-container">
			<ul>
				<% if session[:user_id].nil? %>
					<li><%= link_to 'Login', login_path, :class => 'login', method: :get %></li>
					<li><%= link_to 'New user', new_user_path, :class => 'logout' %></li>
				<% else %>
					<li><%= link_to 'Logout', logout_path, :class => 'logout', method: :get %></li>	
					<li><%= link_to 'Account', edit_user_path(@current_user.id), :class => 'login' %></li>
					<li><%= link_to 'Cart', '/carts/show', :class => 'login' %></li>
				<% end %>
						
			</ul>
		</span>
  	</div>
  	
	
  	
  	<div class='overflow-container'>
	  	<div>
  			<div id='menu-container'>
  				<li><%= link_to 'Artist', root_path, :class => 'main-menu' %></li>
    			<li class="bar">|</li>
  				<li><%= link_to 'Gallery', galleries_path( :search_term => 'all' ), :class => 'main-menu' %></li>
  				<li class="bar">|</li>
    			<li><%= link_to 'Discussion', discussion_path, :class => 'main-menu' %></li>
  				<li class="bar">|</li>
  				<li><%= link_to 'Contact', contact_path, :class => 'main-menu' %></li>
		  	</div>
	  	</div>
  	</div>
  	
	<%= render :partial => '/layouts/sidebar' %>

  	<div class='page-spacing'>
  		<div class="<%= controller.controller_name %>">
    		<%= yield %>
	    </div>
    </div>
    
	
  
  </body>
</html>

app/views/layouts/no_sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiffanysWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  	
	<div class='header-color'>
	</div>

	<div class='header'>
	  	<h1 class='web-header-container'><span class="web-header">T i f f a n y</span><span class="web-header two">N e l s o n</span></h1>
	  	<div class='header-description'><em>artist | metal smith | maker</em></div>
	  	<span class="login-container">
			<ul>
				<% if session[:user_id].nil? %>
					<li><%= link_to 'Login', login_path, :class => 'login', method: :get %></li>
					<li><%= link_to 'New user', new_user_path, :class => 'logout' %></li>
				<% else %>
					<li><%= link_to 'Logout', logout_path, :class => 'logout', method: :get %></li>	
					<li><%= link_to 'Account', edit_user_path(@current_user.id), :class => 'login' %></li>
					<li><%= link_to 'Cart', '/carts/show', :class => 'login' %></li>
				<% end %>
						
			</ul>
		</span>
  	</div>
  	
	
  	
  	<div class='overflow-container'>
	  	<div>
  			<div id='menu-container'>
  				<li><%= link_to 'Artist', root_path, :class => 'main-menu' %></li>
    			<li class="bar">|</li>
  				<li><%= link_to 'Gallery', galleries_path( :search_term => 'all' ), :class => 'main-menu' %></li>
  				<li class="bar">|</li>
    			<li><%= link_to 'Discussion', discussion_path, :class => 'main-menu' %></li>
  				<li class="bar">|</li>
  				<li><%= link_to 'Contact', contact_path, :class => 'main-menu' %></li>
		  	</div>
	  	</div>
  	</div>
  	

  	<div class='page-spacing-full'>
  		<div class="<%= controller.controller_name %>">
    		<%= yield %>
	    </div>
    </div>
    
	
  
  </body>
</html>